---
title: Whole CHS Living
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fran.archila@gmail.com
description: Finding a wholesome & healthy life in Charleston, SC.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: Wholechsliving
markdown: kramdown
gems:
- jekyll-feed
- jekyll/tagging
exclude:
- Gemfile
- Gemfile.lock
_defaults:
  image_path: "/images/placeholder.jpg"
tag_page_layout: tag
tag_page_dir: tags
tag_permalink_style: pretty
